### PR TITLE
Added-flutter-cheatsheet

### PR DESCRIPTION
**Pull request by eshan1925**
Hey added flutter cheatsheet with the ReadME file and the screenshot you asked for.
Thanks

### CODE REVIEW

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
I checked the screenshot. you can delete the screenshot and I'll merge the rest. thanks

**Comment by eshan1925** [comment]
I have removed the screenshot.
Thanks

**Comment by eshan1925** [comment]
Hello,
I noticed that my pull request hasn't been merged from the last 2
days.Anything needs to be updated, do notify me.
Thanks

**Comment by darkmatter18** [comment]
Sorrry for the delay. Was little busy

**Pull request closed without merging**
