### PR TITLE
Uploaded JavaScript Files 

### PR DESCRIPTION
**Pull request by vansh106**
I uploaded a full package for JavaScript.

### CODE REVIEW

**Comment by darkmatter18** [comment]
@vansh106 Thanks a lot for contributing. I love your contribution a lot. 

I just want a little change:
- Just add the links in the javascript readme file
- If you can, make the file names a little smaller

If you have any queries, don't hesitate. Just ask. I am here to help you. Thanks again

**Comment by vansh106** [comment]
Thankyou so And yes i will make changes as soon as possible. 😀

**Comment by vansh106** [comment]
Bhaiya i updated files according to your  required changes. I m very new to github , i m confused why cant i make another pull request OR the changes have been done  previous pull request?

**Comment by vansh106** [comment]
> @vansh106 Thanks a lot for contributing. I love your contribution a lot.
> 
> I just want a little change:
> 
> * Just add the links in the javascript readme file
> * If you can, make the file names a little smaller
> 
> If you have any queries, don't hesitate. Just ask. I am here to help you. Thanks again
I did the changes .Will you merge ?

**Pull request closed without merging**
