### PR TITLE
Added VSCode windows cheatsheet

### PR DESCRIPTION
**Pull request by Kunal1198**
Added VSCode windows cheatsheet.

### CODE REVIEW

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Hey @Kunal1198  , please attach a screenshot of your cheat sheets and please show that in the README file inside the VSCode dir

**Comment by Kunal1198** [comment]
Hi @darkmatter18 I already attached the screenshot of Vscode cheatsheet and now updated the README file inside VSCode directory.

**Comment by Kunal1198** [comment]
Please review my PR

**Review by darkmatter18 — APPROVED** [review]
LSTM! Nice work

**Comment by darkmatter18** [comment]
Hey, @Kunal1198 Thanks for your contribution. 

I know, I was not a good maintainer, but I am trying my best to be a good one.

**Thank You**

**Happy Hacktoberfest**

If you love my initiative and love the Repo, please consider to **STAR** the repo, and ***Follow*** Me on github

Connect with me on [Linkedin](https://www.linkedin.com/in/arkadip/) and [Twitter](https://twitter.com/Arkadipb21)

[forthebadge](https://forthebadge.com)
[forthebadge](https://forthebadge.com)

**Pull request merged**
