### PR TITLE
Add JavaScript cheat sheet pdf

### PR DESCRIPTION
**Pull request by yashi12**
- hyperlinks for all topics
- One liner syntax
- screenshots for promises

Solved Issue (#16)

### CODE REVIEW

**Review by CormacKrum — APPROVED** [review]

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Hey, @yashi12 Please add your file in the `JavaScript` folder's README file. Thanks

**Comment by yashi12** [comment]
@darkmatter18 added cheatsheet to Readme.md, please review it and merge it.

**Comment by yashi12** [comment]
@darkmatter18 please reiview the PR, I have the Readme.md. Thankyou!

**Review by darkmatter18 — APPROVED** [review]
@yashi12 LSTM.

**Comment by darkmatter18** [comment]
Hey, @yashi12 Thanks for your contribution. 

I know, I was not a good maintainer, but I am trying my best to be a good one.

**Thank You**

**Happy Hacktoberfest**

If you love my initiative and love the Repo, please consider to **STAR** the repo, and ***Follow*** Me on github

Connect with me on [Linkedin](https://www.linkedin.com/in/arkadip/) and [Twitter](https://twitter.com/Arkadipb21)

[forthebadge](https://forthebadge.com)
[forthebadge](https://forthebadge.com)

**Pull request merged**
