### PR TITLE
Time complexity cheatsheet added

### PR DESCRIPTION
**Pull request by Naziya-Parveen**
Added a cheatsheet for time complexity of common data structures and sorting algorithms.

### CODE REVIEW

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
@Naziya-Parveen Add the content in main `README.md`

**Comment by Naziya-Parveen** [comment]
@darkmatter18 sure

**Review by darkmatter18 — APPROVED** [review]
@Naziya-Parveen Nice Work. Thanks a lot

**Comment by darkmatter18** [comment]
Hey @Naziya-Parveen, Thanks for your contribution. Hope you like the repo, if you did, then please Star ✨ it. Thanks again.

**Pull request merged**
