### PR TITLE
Vscode cheatsheet

### PR DESCRIPTION
**Pull request by ujjwalsingh-17**
added vs code cheatsheet

### CODE REVIEW

**Comment by darkmatter18** [comment]
Please make the following changes:
1. Change the directory name to `Visual Studio Code` from `Vs Code`
2. Please add file links in the Visual Studio Code/README.md 

Will marge after the changes

**Comment by ujjwalsingh-17** [comment]
Ok sir.

**Comment by ujjwalsingh-17** [comment]
@darkmatter18 sir i made changes as directed by you. Could you please have a look to that and guide me further.

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Please move the file to `Code Editors/Visual Studio Code` and Add the link there

**Comment by darkmatter18** [comment]
Please don't call me sir. Just call me Bro or Brother or Buddy. 😊

**Review by darkmatter18 — APPROVED** [review]

**Pull request merged**
