### PR TITLE
added Powershell Cheat Sheet and Readme

### PR DESCRIPTION
**Pull request by ChrisIIx**
Hi,

added a Powershell Folder and uploaded first Cheat Sheet with Readme.

Tag me if further help needed. ! :) 

KR,
ChrisIIx

### CODE REVIEW

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Nice Work @ChrisIIx. Just make a little refactoring. 

- Make a directory named `Shells`.
- Inside that make a directory named `Powershell` and add your Cheatsheet
- Place your `README` in `Shells` dir.
- Add a New Content in main the `README`  file named `Shells` and under that `Powershell` and point that to for forlder

**Comment by ChrisIIx** [comment]
Hey, 
thanks for the hints.

Made changes according to your information 👍

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Hey@ChrisIIx, Everything is ok, just Remove ` Powershell/Powershell Cheat-sheet.pdf` and `Powershell/Readme.md`, `Shell/.DS_Store`.

**Comment by ChrisIIx** [comment]
Hi @darkmatter18 ,

sorry for the delay and confusing, have forgot git add -u in order to catch the removed files. (still learning :) ) 
Pull should now only focus the related documents.

If anything other still occurs, feel free to give me feedback.

**Comment by ChrisIIx** [comment]
Hey @darkmatter18 ,

could you look into the PR or add the label "hacktoberfest-accepted" to the PR ?

Thank you and kind regards,
ChrisIIx

**Review by darkmatter18 — APPROVED** [review]

**Comment by darkmatter18** [comment]
@ChrisIIx Nice work 🎉🎊 Please don't forget to star ✨ the repo.

**Comment by ChrisIIx** [comment]
Done 👍 Thank you 🎊

**Pull request merged**
