### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by jrmy911**
Let me know what u think of this. :)

### CODE REVIEW

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Just remove the .DS_Store files, and we are good to go

**Comment by jrmy911** [comment]
Should be good. Can you check?

**Comment by jrmy911** [comment]
@darkmatter18 Are we still waiting for something? :)

**Comment by darkmatter18** [comment]
Sorry buddy. Was little busy. I'll go through and let you know.

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
Remove these 2 files

[cli/shell/.DS_Store](https://github.com/darkmatter18/cheatsheet/pull/163/files#diff-c90099676c0dacccbd5a0b861255c0e326d74c2b06d9ac7dc75ea0497d06ea95)
[images/.DS_Store](https://github.com/darkmatter18/cheatsheet/pull/163/files#diff-97b0456aeb72a56519efafa1953ac38ef89f5c79274b808d5fa9dd991a4609c9)

**Comment by jrmy911** [comment]
Done @darkmatter18!

**Pull request merged**
